name: glossario_de_oclusao
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter_native_splash: ^2.4.0
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  cloud_firestore: ^4.17.2
  firebase_auth: ^4.19.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#2196F3"
  image: assets/images/logo_splash.png


flutter:
  uses-material-design: true
  
  assets:
    - assets/images/dente_logo.png
    - assets/images/logo_splash.png