// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMbznqi4oJrjumyWfF30k9a7LxhW4D9CY',
    appId: '1:1043662098458:web:9818e19c879d379cab41a3',
    messagingSenderId: '1043662098458',
    projectId: 'glossario-de-oclusao-e7a08',
    authDomain: 'glossario-de-oclusao-e7a08.firebaseapp.com',
    storageBucket: 'glossario-de-oclusao-e7a08.appspot.com',
    measurementId: 'G-R68LFZ9KQP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAubKiNOFTdhNT_cdls5HTLwAKc53iZ9HY',
    appId: '1:1043662098458:android:a507bbcafc587697ab41a3',
    messagingSenderId: '1043662098458',
    projectId: 'glossario-de-oclusao-e7a08',
    storageBucket: 'glossario-de-oclusao-e7a08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrSFIGnWhV7dEQDDHbecZbl9iDwxLrCiI',
    appId: '1:1043662098458:ios:36507aea0bdfacd6ab41a3',
    messagingSenderId: '1043662098458',
    projectId: 'glossario-de-oclusao-e7a08',
    storageBucket: 'glossario-de-oclusao-e7a08.appspot.com',
    iosBundleId: 'com.example.glossarioDeOclusao',
  );
}
